# Generated by Django 4.0.2 on 2023-03-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.URLField()),
                ('birthdate', models.DateField()),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
                ('is_visible', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('allow_contact', models.BooleanField()),
                ('challenge', models.TextField()),
            ],
        ),
    ]
