# Generated by Django 4.0.2 on 2023-03-25 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('previous_role', models.CharField(max_length=200)),
                ('current_role', models.CharField(max_length=200)),
                ('profile_image', models.URLField()),
                ('birthdate', models.DateField()),
                ('pronouns', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
                ('is_visible', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('allow_contact', models.BooleanField()),
                ('challenge', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='profiles.profile')),
            ],
        ),
    ]
